export { default as Main } from './Main';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as ForgetPassword } from './ForgetPassword';
export { default as Info } from './Info';
export { default as Todo } from './Todo';
export { default as Description } from './Description';
export { default as Privacy } from './Privacy';
export { default as App } from './App';