export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";

/* PLAN CRUD(Create Read Update Delete) */ 
export const PLAN_POST = "PLAN_POST";
export const PLAN_POST_SUCCESS = "PLAN_POST_SUCCESS";
export const PLAN_POST_FAILURE = "PLAN_POST_FAILURE";
export const PLAN_GET = "PLAN_GET";
export const PLAN_GET_SUCCESS = "PLAN_GET_SUCCESS";
export const PLAN_GET_FAILURE = "PLAN_GET_FAILURE";
export const PLAN_UPDATE = "PLAN_UPDATE";
export const PLAN_UPDATE_SUCCESS = "PLAN_UPDATE_SUCCESS";
export const PLAN_UPDATE_FAILURE = "PLAN_UPDATE_FAILURE";
export const PLAN_DELETE = "PLAN_DELETE";
export const PLAN_DELETE_SUCCESS = "PLAN_DELETE_SUCCESS";
export const PLAN_DELETE_FAILURE = "PLAN_DELETE_FAILURE";
export const USER_INFO_GET = "USER_INFO_GET";
export const USER_INFO_GET_SUCCESS = "USER_INFO_GET_SUCCESS";
export const USER_INFO_GET_FAILURE = "USER_INFO_GET_FAILURE";
export const USER_INFO_UPDATE = "USER_INFO_UPDATE";
export const USER_INFO_UPDATE_SUCCESS = "USER_INFO_UPDATE_SUCCESS";
export const USER_INFO_UPDATE_FAILURE = "USER_INFO_UPDATE_FAILURE";